keys:
  - &desktop age1j3t4lmggn2k7cguw9ud9ch7pqq3dxknj4m82s8c7wr8cz5xt7uasnkdjat
  - &desktop_host_key age1hj3692ukgdfltp00szfncyfxzdx4769yx6dp68dhgd368vj6ushqppyyhc
  - &server age1yzrcyvngvwzlp7qpz6kcwwmj935jmvyp6n2wtq7epug2r5lm5vrqt4e8k5
  - &server_host_key age1aclvh35y6uqps83qw3u5j2c7fpqkc8snsxddmsfvz6wxl3yfy47saqs86d
  - &cloud age1kvkmmmkf8ajy64umcle2vkjysry3tgdqnzsllakramp32mwzgc6qget36g
  - &cloud_host_key age17l3jvgx6rnkgw5lt8pttfwx50pj009g3hfjl3qz6c3uk3kvlv5wq8wj6mm
creation_rules:
  - path_regex: common/defaults/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *desktop
        - *desktop_host_key
        - *server
        - *server_host_key
        - *cloud
        - *cloud_host_key
  - path_regex: desktop/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *desktop
        - *desktop_host_key
  - path_regex: server/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *server
        - *server_host_key
  - path_reqex: cloud/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *cloud
        - *cloud_host_key
  - path_regex: cloud/containers/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *cloud
        - *cloud_host_key
